version: '3.9'
services:
  seerr-notifier:
    image: seerr-notifier:latest
    container_name: seerr-notifier
    ports:
      - "8787:8787" # <Host Port>:<Container Port (do not change)>
    volumes:
      - ./config:/app/config
      - ./templates:/app/templates
    tty: true
    stdin_open: true
    restart: unless-stopped